# Install gitlab through docker
---
- hosts: all
  become: true

  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: ubuntu:bionic
              
    - name: create gitlab directories
      file: path={{item}} recurse=yes state=directory
      loop: ['/srv/gitlab/config', '/srv/gitlab/logs', '/srv/gitlab/data']

    - name: Install Gitlab container
      docker_container:
        name: gitlab
        image: gitlab/gitlab-ce:latest
        state: started
        ports: 
          - "1122:22"
          - "1180:80"
          - "11443:443"
        volumes:
          - "/srv/gitlab/config:/etc/gitlab"
          - "/srv/gitlab/logs:/var/log/gitlab"
          - "/srv/gitlab/data:/var/opt/gitlab"
        restart_policy: always      
