#!/usr/bin/env python3
import requests, sys

private_token = 'V4vrMhNvRpFdD2-cyv4R'
gl_users_api_url = 'http://192.168.0.2:1180/api/v4/users'
headers = {'PRIVATE-TOKEN': private_token}
parm_username = 'username'

def print_usage():
    print('Usage: gitlab-user-find username')
    print('Requires private token to be set up in script')

if (len(sys.argv) != 2):
    print_usage()
    exit()

username = sys.argv[1]
request_str = gl_users_api_url + '?' + parm_username + '=' + username
#Print(request_str)
r = requests.get(request_str, headers=headers)
if (r.status_code != 200):
    print('Error ', r.status_code)
    exit()

for user in r.json():
    print('Username: ' + user["username"])
    print('Email: ' + user["email"])
    print('Name: ' + user["name"])
    print('State: ' + user["state"])


